apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uum8ishtt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uum8ishtt-nodejs 
  name: uum8ishtt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uum8ishtt-nodejs 
